import { Link } from "wouter";
import { Zap, Rocket, Code2, Globe, CreditCard, Users, BarChart3, ShoppingCart, GraduationCap, Sparkles, ArrowRight, CheckCircle2, ChevronRight } from "lucide-react";

const features = [
  { icon: Sparkles, title: "AI-Powered Generation", description: "Describe your SaaS in plain English. Our AI writes the full codebase — frontend, backend, and database schema — in seconds." },
  { icon: Rocket, title: "One-Click Deploy", description: "Push to Vercel, Netlify, or Replit instantly. Zero DevOps knowledge required. Go from idea to live URL in under a minute." },
  { icon: Code2, title: "Full Source Access", description: "Every generated project gives you the complete, clean source code. Customize anything — no black boxes, no lock-in." },
  { icon: Globe, title: "12+ Starter Templates", description: "CRM, LMS, E-commerce, AI tools, marketplaces and more. Each template is a production-ready starting point, not a toy demo." },
  { icon: Users, title: "Team Collaboration", description: "Invite your team to projects. Assign roles, review generated code, and ship together with built-in access controls." },
  { icon: BarChart3, title: "Usage Analytics", description: "Track your credit consumption, deployment history, and project health from a single command-center dashboard." },
];

const templates = [
  { icon: Users, name: "CRM Platform", desc: "Pipeline & contacts", id: "crm" },
  { icon: GraduationCap, name: "Learning Platform", desc: "Courses & students", id: "lms" },
  { icon: ShoppingCart, name: "E-commerce", desc: "Store & checkout", id: "ecommerce" },
  { icon: BarChart3, name: "Analytics Dashboard", desc: "Metrics & insights", id: "analytics" },
  { icon: Sparkles, name: "AI Tool", desc: "Prompt & results", id: "ai-tool" },
  { icon: Rocket, name: "SaaS Starter", desc: "Auth & billing ready", id: "saas-starter" },
];

const pricingTiers = [
  {
    name: "Free",
    price: "$0",
    period: "forever",
    features: ["1 project", "10 AI credits/month", "Community templates", "Manual deploy"],
    cta: "Get started free",
    highlight: false,
  },
  {
    name: "Starter",
    price: "$29",
    period: "/ month",
    features: ["3 projects", "100 AI credits/month", "All templates", "One-click deploy", "Priority support"],
    cta: "Start building",
    highlight: true,
  },
  {
    name: "Pro",
    price: "$79",
    period: "/ month",
    features: ["10 projects", "500 AI credits/month", "Team collaboration", "Advanced AI models", "API access", "Analytics"],
    cta: "Go Pro",
    highlight: false,
  },
  {
    name: "Enterprise",
    price: "$199",
    period: "/ month",
    features: ["Unlimited projects", "2000 AI credits/month", "White-label", "Dedicated infra", "SLA guarantee", "24/7 support"],
    cta: "Contact us",
    highlight: false,
  },
];

export default function Landing() {
  return (
    <div className="pt-16">
      {/* Hero */}
      <section className="relative min-h-[90vh] flex items-center overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_hsl(180_100%_50%_/_0.07)_0%,_transparent_70%)]" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full bg-primary/5 blur-3xl pointer-events-none" />
        <div className="max-w-6xl mx-auto px-6 py-24 relative z-10">
          <div className="inline-flex items-center gap-2 border border-primary/30 bg-primary/10 text-primary text-xs font-medium px-3 py-1 rounded-full mb-8">
            <Zap className="w-3 h-3" />
            AI-powered SaaS generation is here
          </div>
          <h1 className="text-5xl md:text-7xl font-bold tracking-tight leading-none mb-6">
            Build any SaaS<br />
            <span className="text-primary">in minutes.</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-xl mb-10 leading-relaxed">
            Describe your product. Get a complete, deployable SaaS — frontend, backend, database, and billing — generated by AI and ready to ship.
          </p>
          <div className="flex flex-col sm:flex-row gap-4">
            <Link href="/dashboard" className="flex items-center justify-center gap-2 bg-primary text-primary-foreground px-6 py-3 rounded-md font-semibold hover:opacity-90 transition-opacity text-sm">
              Start building free <ArrowRight className="w-4 h-4" />
            </Link>
            <Link href="/templates" className="flex items-center justify-center gap-2 border border-border text-foreground px-6 py-3 rounded-md font-medium hover:border-primary/50 hover:text-primary transition-colors text-sm">
              Browse templates
            </Link>
          </div>
          <div className="mt-14 flex items-center gap-8 flex-wrap">
            {["No code required", "Deploy in 60 seconds", "Full source code", "Cancel anytime"].map(text => (
              <div key={text} className="flex items-center gap-2 text-sm text-muted-foreground">
                <CheckCircle2 className="w-4 h-4 text-primary shrink-0" />
                {text}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats bar */}
      <section className="border-y border-border bg-card/50">
        <div className="max-w-6xl mx-auto px-6 py-8 grid grid-cols-2 md:grid-cols-4 gap-8">
          {[
            { value: "12,000+", label: "Products generated" },
            { value: "4.2 min", label: "Average generation time" },
            { value: "99.8%", label: "Deploy success rate" },
            { value: "50+", label: "AI model options" },
          ].map(({ value, label }) => (
            <div key={label} className="text-center">
              <div className="text-2xl font-bold text-primary mb-1">{value}</div>
              <div className="text-xs text-muted-foreground">{label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Everything you need to ship</h2>
            <p className="text-muted-foreground max-w-lg mx-auto">From idea to production, SaaS Factory handles every layer of your product stack.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map(({ icon: Icon, title, description }) => (
              <div key={title} className="border border-border rounded-xl p-6 bg-card hover:border-primary/40 transition-colors group">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                  <Icon className="w-5 h-5 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">{title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-24 bg-card/30 border-y border-border">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">From idea to live in 3 steps</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { step: "01", title: "Describe your SaaS", desc: "Type a plain-English description of your product. Choose a template or start from scratch." },
              { step: "02", title: "AI generates everything", desc: "Our AI writes the complete codebase — React frontend, Express API, PostgreSQL schema, Stripe billing." },
              { step: "03", title: "Deploy with one click", desc: "Push to Vercel, Netlify, or Replit. Your live URL is ready in under 60 seconds." },
            ].map(({ step, title, desc }) => (
              <div key={step} className="relative">
                <div className="text-6xl font-black text-primary/15 mb-4 font-mono">{step}</div>
                <h3 className="text-lg font-semibold mb-2">{title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Templates */}
      <section id="templates" className="py-24">
        <div className="max-w-6xl mx-auto px-6">
          <div className="flex items-end justify-between mb-12">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold mb-3">Start with a template</h2>
              <p className="text-muted-foreground">Production-ready starting points for any SaaS category.</p>
            </div>
            <Link href="/templates" className="hidden md:flex items-center gap-1 text-sm text-primary hover:opacity-80 transition-opacity">
              View all <ChevronRight className="w-4 h-4" />
            </Link>
          </div>
          <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
            {templates.map(({ icon: Icon, name, desc, id }) => (
              <Link key={name} href={`/dashboard/new?template=${id}`} className="border border-border rounded-xl p-5 bg-card hover:border-primary/50 hover:bg-card/80 transition-all group cursor-pointer flex items-center gap-4">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 group-hover:bg-primary/20 transition-colors">
                  <Icon className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <div className="font-medium text-sm">{name}</div>
                  <div className="text-xs text-muted-foreground">{desc}</div>
                </div>
                <ArrowRight className="w-4 h-4 text-muted-foreground ml-auto opacity-0 group-hover:opacity-100 transition-opacity" />
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 bg-card/30 border-y border-border">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Simple, transparent pricing</h2>
            <p className="text-muted-foreground">Start free. Scale as you ship.</p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {pricingTiers.map(({ name, price, period, features, cta, highlight }) => (
              <div key={name} className={`rounded-xl p-6 border flex flex-col ${highlight ? "border-primary bg-primary/5 relative" : "border-border bg-card"}`}>
                {highlight && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-primary text-primary-foreground text-xs font-semibold px-3 py-1 rounded-full">
                    Most popular
                  </div>
                )}
                <div className="mb-6">
                  <div className="text-sm font-medium text-muted-foreground mb-2">{name}</div>
                  <div className="flex items-end gap-1">
                    <span className="text-3xl font-bold">{price}</span>
                    <span className="text-muted-foreground text-sm mb-1">{period}</span>
                  </div>
                </div>
                <ul className="space-y-2.5 flex-1 mb-6">
                  {features.map(f => (
                    <li key={f} className="flex items-start gap-2 text-sm">
                      <CheckCircle2 className={`w-4 h-4 shrink-0 mt-0.5 ${highlight ? "text-primary" : "text-muted-foreground"}`} />
                      {f}
                    </li>
                  ))}
                </ul>
                <Link href="/dashboard" className={`w-full flex items-center justify-center py-2 rounded-md text-sm font-medium transition-opacity hover:opacity-90 ${highlight ? "bg-primary text-primary-foreground" : "border border-border text-foreground hover:border-primary/50"}`}>
                  {cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24">
        <div className="max-w-3xl mx-auto px-6 text-center">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Your next SaaS is<br /><span className="text-primary">one prompt away.</span>
          </h2>
          <p className="text-muted-foreground mb-8 text-lg">Join thousands of builders who ship products faster with SaaS Factory.</p>
          <Link href="/dashboard" className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-8 py-4 rounded-md font-semibold text-sm hover:opacity-90 transition-opacity">
            Start building for free <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>
    </div>
  );
}
